[output]
operational_cost_per_scenario = "operational_costs.csv"
loss_of_load = "loss_of_load.csv"
scalars = "scalars.toml"
investment = "investment.csv"
production = "production.csv"
line_flow = "line_flow.csv"
dir = "output_1900_"

[input.sets]
scenarios = ["1900", "1992"]
locations = "auto"
generators = "auto"
periods = "1:10"
transmission_lines = "auto"
period_duration = 24

[input.rp]
number_of_periods = 10
clustering_type = "cross_scenario"
method = "conical_unbounded"
distance = "SqEuclidean"
use_periods = true
blended = false

[input.data]
transmission_lines = "transmission_lines.csv"
generation = "generation.csv"
scenario_probabilities = "auto"
scalars = "scalars.toml"
demand = "demand.csv"
generation_availability = "generation_availability.csv"
dir = "inputs"
seed = "seeds.json"

[input.fixed]
fixed_run = false
