[input.data]
# input directory with the files
dir = "inputs"
demand = "demand.csv"
generation_availability = "generation_availability.csv"
generation = "generation.csv"
transmission_lines = "transmission_lines.csv"
scalars = "scalars.toml"
scenario_probabilities = "auto"

[input.sets]
time_steps = 720
scenarios = ["1900"]
locations = "auto"
transmission_lines = "auto"
generators = "auto"

[input.rp]
use_periods = true
number_of_periods = 1
period_duration = 720
clustering_type = "completescenario"

[output]
dir = "output"
investment = "investment.csv"
production = "production.csv"
line_flow = "line_flow.csv"
loss_of_load = "loss_of_load.csv"
scalars = "scalars.toml"
